services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: toyshop
      MYSQL_USER: prac8
      MYSQL_PASSWORD: '1234'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./toyshop:/app
    ports:
      - "8000:8000"
    environment:
#      - DJANGO_SETTINGS_MODULE=toyshop.settings
      - DATABASE_URL=mysql://prac8:1234@db:3306/toyshop
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
