# Generated by Django 5.1.2 on 2024-12-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_myuser_expandeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpandedUser',
        ),
    ]
