# Generated by Django 5.1.4 on 2024-12-14 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_delete_expandeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(choices=[('Русский', 'Ru'), ('English', 'Eng')], default='Русский', max_length=10)),
                ('them', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
            ],
        ),
    ]
